version: '3.9'

services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_service
    ports:
      - "5433:5432"
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge