eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

server:
    port: 8080