eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: authentication-service

    #Database PostrgreSQL
    datasource:
      url: jdbc:postgresql://localhost:5433/auth_service
      username: auth_user
      password: auth_password
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      show-sql: true

    #Security
security:
  jwt:
    secret_key: c39d70463be1a5a035db4cf1f655d59434cdc5c34b29f1c25bc6a21ad3c25e22
    access_token_expiration: 3600000 # 1 hours
    refresh_token_expiration: 604800000 # 7 days

server:
    port: 8081