spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri:
        native:
          search-locations: file:src/main/resources/configurations-docker

server:
  port: 8888
